[package]
name = "webext-storage-ffi"
version = "0.1.0"
authors = [ "The Firefox Sync Developers <sync-team@mozilla.com>",]
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"

[lib]
name = "webext_storage_ffi"
crate-type = [ "lib",]

[dependencies]
lazy_static = "1.5.0"
ffi-support = "0.4.4"
serde_json = "1.0.145"

[dependencies.error-support]
path = "../../support/error"

[dependencies.webext-storage]
path = ".."
