[package]
name = "start-bindings"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
anyhow = "1.0.98"
camino = "1.1.10"
cargo_metadata = "0.21.0"
rinja = "0.4.0+deprecated"
serde_yaml = "0.9.34+deprecated"
toml = "0.9.4"
toml_edit = "0.23.2"

[dependencies.clap]
version = "4.5.41"
features = [ "derive",]
