[package]
name = "error-support-macros"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
proc-macro2 = "1.0.95"

[dependencies.syn]
version = "2.0.104"
features = [ "derive", "parsing", "full",]
