[[example]]
name = "tabs-sync"
path = "src/tabs-sync.rs"

[package]
name = "example-tabs-sync"
version = "0.1.0"
authors = [ "sync-team@mozilla.com",]
license = "MPL-2.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dev-dependencies]
base64 = "0.23.2"
serde_json = "1.0.145"
log = "0.4.27"
anyhow = "1.0.98"
chrono = "0.4.41"
structopt = "0.3.26"
url = "2.5.4"

[dev-dependencies.tabs]
path = "../../components/tabs"

[dev-dependencies.cli-support]
path = "../cli-support"

[dev-dependencies.interrupt-support]
path = "../../components/support/interrupt"

[dev-dependencies.sync15]
path = "../../components/sync15"
features = [ "sync-engine",]

[dev-dependencies.viaduct-reqwest]
path = "../../components/support/viaduct-reqwest"
