[package]
name = "examples-suggest-cli"
version = "0.1.0"
license = "MPL-2.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
log = "0.4.27"
anyhow = "1.0.98"

[dependencies.cli-support]
path = "../cli-support"

[dependencies.remote_settings]
path = "../../components/remote_settings"

[dependencies.viaduct-reqwest]
path = "../../components/support/viaduct-reqwest"

[dependencies.clap]
version = "4.5.41"
features = [ "derive",]

[dependencies.suggest]
path = "../../components/suggest"

[dependencies.env_logger]
version = "0.11.8"
default-features = false
features = [ "humantime",]

[dependencies.nss]
version = "0.1.0"
path = "../../components/support/rc_crypto/nss"
