[package]
name = "nimbus-cli"
version = "0.5.0"
edition = "2024"
rust-version = "1.85.0"
authors = [ "Nimbus SDK Engineering",]
license = "MPL-2.0"

[features]
default = [ "server",]
server = [ "dep:axum", "dep:tokio", "dep:tower", "dep:tower-http", "dep:tower-livereload", "dep:hyper", "dep:local-ip-address",]

[dependencies]
anyhow = "1.0.98"
serde_json = "1.0.145"
thiserror = "2.0.12"
unicode-segmentation = "1.12.0"
console = "0.16.0"
glob = "0.3.2"
heck = "0.5.0"
whoami = "2.0.0-pre.2"
serde_yaml = "0.9.34+deprecated"
percent-encoding = "2.3.1"
copypasta = "0.10.2"
chrono = "0.4.41"

[dependencies.clap]
version = "4.5.42"
features = [ "derive",]

[dependencies.remote_settings]
path = "../../remote_settings"

[dependencies.nimbus-fml]
path = "../nimbus-fml"
features = [ "client-lib",]

[dependencies.serde]
version = "1.0.221"
features = [ "derive",]

[dependencies.viaduct-reqwest]
path = "../viaduct-reqwest"

[dependencies.update-informer]
version = "1.3.0"
default-features = false

[dependencies.reqwest]
version = "0.12.22"
default-features = false
features = [ "blocking", "native-tls-vendored", "gzip", "json",]

[dependencies.axum]
version = "0.8.4"
optional = true

[dependencies.tokio]
version = "1.52.0"
optional = true
features = [ "sync", "rt", "macros",]

[dependencies.tower]
version = "0.5.2"
optional = true

[dependencies.tower-http]
version = "0.6.6"
optional = true
features = [ "fs", "set-header",]

[dependencies.tower-livereload]
version = "0.9.6"
optional = true

[dependencies.hyper]
version = "1.6.0"
optional = true
features = [ "server",]

[dependencies.local-ip-address]
version = "0.6.5"
optional = true
