[package]
name = "viaduct-reqwest"
version = "0.2.0"
authors = [ "Sync Team <sync-team@mozilla.com>",]
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"

[lib]
crate-type = [ "lib",]

[dependencies]
once_cell = "1.21.3"

[dependencies.error-support]
path = "../error"

[dependencies.viaduct]
path = "../../viaduct"

[dependencies.reqwest]
version = "0.12.22"
features = [ "blocking", "native-tls-vendored",]
