[package]
name = "rust-log-forwarder"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
authors = [ "Sync Team <sync-team@mozilla.com>",]
license = "MPL-2.0"
exclude = [ "/android", "/ios",]

[dev-dependencies]
tracing = "0.1.41"

[dependencies.uniffi]
version = "0.29.4"

[dependencies.error-support]
path = "../error"
default-features = false
features = [ "tracing-logging",]

[dependencies.tracing-subscriber]
version = "0.3.19"
default-features = false
features = [ "fmt", "std",]

[dependencies.tracing-support]
path = "../tracing"

[build-dependencies.uniffi]
version = "0.29.4"
features = [ "build",]
