[package]
name = "types"
version = "0.1.0"
authors = [ "Sync Team <sync-team@mozilla.com>",]
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.145"

[dependencies.rusqlite]
version = "0.37.0"
features = [ "functions", "bundled",]
