[package]
name = "firefox-versioning"
version = "0.1.0"
authors = [ "Nimbus Team <project-nimbus@mozilla.com>",]
license = "MPL-2.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
serde_json = "1.0.145"
thiserror = "2.0.12"
