[package]
name = "nss_sys"
version = "0.1.0"
authors = [ "Sync Team <sync-team@mozilla.com>",]
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"

[lib]
crate-type = [ "lib",]

[features]
default = []
gecko = []

[dependencies.libsqlite3-sys]
version = "0.35.0"
features = [ "bundled",]

[build-dependencies.nss_build_common]
path = "../nss_build_common"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [ "cfg(__appsvc_ci_hack)",]
