[package]
name = "error-support"
version = "0.1.0"
authors = [ "Thom Chiovoloni <tchiovoloni@mozilla.com>",]
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"
autotests = false
exclude = [ "/android",]

[features]
backtrace = [ "dep:backtrace",]
tracing-logging = [ "dep:tracing", "dep:tracing-support",]
tracing-reporting = [ "dep:tracing", "dep:tracing-support",]
testing = [ "tracing-support/testing",]

[dependencies.backtrace]
version = "0.3.75"
optional = true

[dependencies.error-support-macros]
path = "macros"

[dependencies.env_logger]
version = "0.11.8"
default-features = false

[dependencies.lazy_static]
version = "1.5.0"

[dependencies.log]
version = "0.4.27"

[dependencies.parking_lot]
version = "0.12.4"

[dependencies.tracing]
version = "0.1.41"
optional = true

[dependencies.tracing-support]
path = "../tracing"
optional = true

[dependencies.uniffi]
version = "0.29.4"

[build-dependencies.uniffi]
version = "0.29.4"
features = [ "build",]
