[package]
name = "megazord"
version = "0.1.0"
authors = [ "Sync Team <sync-team@mozilla.com>",]
edition = "2024"
rust-version = "1.85.0"
license = "MPL-2.0"

[lib]
crate-type = [ "cdylib",]

[dependencies]
lazy_static = "1.5.0"

[dependencies.fxa-client]
path = "../../components/fxa-client"

[dependencies.logins]
path = "../../components/logins"

[dependencies.tabs]
path = "../../components/tabs/"

[dependencies.sync_manager]
path = "../../components/sync_manager/"

[dependencies.places]
path = "../../components/places"

[dependencies.push]
path = "../../components/push"

[dependencies.remote_settings]
path = "../../components/remote_settings"

[dependencies.rust-log-forwarder]
path = "../../components/support/rust-log-forwarder"

[dependencies.viaduct]
path = "../../components/viaduct"

[dependencies.nimbus-sdk]
path = "../../components/nimbus"

[dependencies.autofill]
path = "../../components/autofill"

[dependencies.crashtest]
path = "../../components/crashtest"

[dependencies.error-support]
path = "../../components/support/error"

[dependencies.suggest]
path = "../../components/suggest"

[dependencies.search]
path = "../../components/search"

[dependencies.tracing-support]
path = "../../components/support/tracing"

[dependencies.init_rust_components]
path = "../../components/init_rust_components"

[dependencies.merino]
path = "../../components/merino"

[dependencies.relay]
path = "../../components/relay"
