[package]
name = "interrupt-support"
version = "0.1.0"
authors = [ "Sync Team <sync-team@mozilla.com>",]
license = "MPL-2.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
lazy_static = "1.5.0"
parking_lot = "0.12.4"

[dependencies.rusqlite]
version = "0.37.0"
features = [ "functions", "limits", "bundled", "unlock_notify",]

[dependencies.uniffi]
version = "0.29.4"

[build-dependencies.uniffi]
version = "0.29.4"
features = [ "build",]
